# Environment settings
env_name: "Ant-v5"
render_mode: None

# Run settings
seed: 0
num_workers: 5  # Number of parallel workers
num_iterations: 1000  # Total number of iterations to run
timesteps_per_iteration: 2048  # Timesteps per iteration
target_sparsity:
  policy: [0.80, 0.80] 
  value: [0.80, 0.80]   
T_start: 0
T_end: 950
update_interval: 100  # Number of iterations between network adjustments
average_interval: 4  # Number of iterations between global averaging and evaluation


# Model settings
algorithm: "PPO"  # Algorithm to use
policy_kwargs:
  activation_fn: "SiLU"  # Activation function for the network
  net_arch: {
    pi: [256, 256],  # Architecture for the policy network
    vf: [256, 256]   # Architecture for the value function network
  }

# Device settings
device: "cpu"  # Device to run the model on (options: "cpu" or "cuda")

# Logging settings
logdir: "logs"  # Directory to save checkpoints and models
